# Generated by Django 4.2.16 on 2026-09-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2000)),
                ('title', models.CharField(max_length=500)),
                ('duration', models.FloatField(help_text='Duration in seconds (ffprobe).')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('has_audio', models.BooleanField(default=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbs/')),
                ('file', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
