# Generated by Django 4.2.16 on 2026-09-15 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('rank', models.PositiveIntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('stream_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('stream_type', models.CharField(default='none', max_length=10)),
                ('thumbnail', models.URLField(blank=True, max_length=2000, null=True)),
                ('duration', models.FloatField(default=0.0)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('volume', models.FloatField(default=1.0)),
                ('hd_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('hd_file', models.FileField(blank=True, null=True, upload_to='hd_clips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rank', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StylePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
